networks:
  default:

services:
  server1:
    container_name: server1
    networks:
      - default
    build:
      context: ./M321-Counter-Backend
      dockerfile: Dockerfile
      args:
        PORT: 5000
        HOST: "0.0.0.0"
        OTHER_SERVERS: "server2:5001,server3:5002"

  server2:
    container_name: server2
    networks:
      - default
    build:
      context: ./M321-Counter-Backend
      dockerfile: Dockerfile
      args:
        PORT: 5001
        HOST: "0.0.0.0"
        OTHER_SERVERS: "server1:5000,server3:5002"

  server3:
    container_name: server3
    networks:
      - default
    build:
      context: ./M321-Counter-Backend
      dockerfile: Dockerfile
      args:
        PORT: 5002
        HOST: "0.0.0.0"
        OTHER_SERVERS: "server1:5000,server2:5001"

  nginx:
    image: nginx:latest
    networks:
      - default
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - server1
      - server2
      - server3

